#!/usr/bin/env python

import rospy
from sensor_msgs.msg import JointState

from markers import *
from funcion_derecho import *

rospy.init_node("testForwardKinematics")
pub = rospy.Publisher('joint_states', JointState, queue_size=1000)
bmarker = BallMarker(color['GREEN'])

# Joint names
jnames = ['joint_1D', 'joint_2D','joint_3D','joint_4D','joint_5D','joint_6D']
# Joint Configuration
#q = np.array([0,0,0,0,0,0])

q = np.array([0.0,-0.08,1.21,0.48,-0.12,-0.85])
# End effector with respect to the base
T = fkine(q)
print( np.round(T, 3) )
print(np.round(TF2xyzquat(T),3))
bmarker.position(T)

# Object (message) whose type is JointState
jstate = JointState()
# Set values to the message
jstate.header.stamp = rospy.Time.now()
jstate.name = jnames
# Add the head joint value (with value 0) to the joints
jstate.position = q

# Loop rate (in Hz)
rate = rospy.Rate(1000)
# Continuous execution loop
while not rospy.is_shutdown():
    # Current time (needed for ROS)
    jstate.header.stamp = rospy.Time.now()
    # Publish the message
    pub.publish(jstate)
    bmarker.publish()
    # Wait for the next iteration
    rate.sleep()
